stages:
    - build
    - deploy

build-test:
    stage: build
    image: local-python-nodejs-cairo
    script:
        - apt-get install --assume-yes python3-cffi
        - export PATH=/opt/node/bin:$PATH
        - python3 -m venv .venv
        - . .venv/bin/activate
        - npm install
        - python3 setup.py install
        - DJANGO_SETTINGS_MODULE=ams.settings.dev ./manage.py migrate
    only:
        - master

push:
    stage: deploy
    image: local-git-ssh
    before_script:
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - 'echo "$STAGING_PRIVATE_KEY" > ~/.ssh/id_ed25519'
        - chmod 600 ~/.ssh/id_ed25519
    script:
        - git remote add deploy gl-amsalgo@obrien.akvorrat.at:/home/git/amsalgorithmus.at || true
        - git push --force deploy HEAD:master
    only:
        - master
