# Generated by Django 2.2 on 2020-04-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-Mail')),
                ('token', models.CharField(max_length=24, unique=True)),
                ('emails_sent', models.IntegerField(default=0)),
                ('withdrawal_emails_sent', models.IntegerField(default=0)),
                ('withdrawal_token', models.CharField(blank=True, max_length=24, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Unterschrift',
                'verbose_name_plural': 'Unterschriften',
            },
        ),
    ]
